<?php

declare(strict_types=1);

namespace PaymosWooCommerce;

use Paymos\Client;
use Paymos\ClientConfig;
use Paymos\Exception\ApiException;

defined('ABSPATH') || exit;

final class Gateway extends \WC_Payment_Gateway
{
    public function __construct()
    {
        $this->id = 'paymos';
        $this->method_title = __('Paymos', 'paymos-woocommerce');
        $this->method_description = __('Accept stablecoin payments through Paymos.', 'paymos-woocommerce');
        $this->icon = apply_filters(
            'woocommerce_paymos_icon',
            plugins_url('assets/img/paymos.svg', PAYMOS_WC_PLUGIN_FILE)
        );
        $this->has_fields = false;
        $this->supports = array('products');

        $this->init_form_fields();
        $this->init_settings();

        $this->title = $this->get_option('title', __('Pay with stablecoins', 'paymos-woocommerce'));
        $this->description = $this->get_option('description', __('Pay with USDT, USDC, DAI and other stablecoins on Tron, Ethereum, BSC, Polygon, Arbitrum, Optimism, Base or TON. No price volatility, no chargebacks, settlement on-chain in minutes.', 'paymos-woocommerce'));
        $this->enabled = $this->get_option('enabled', 'no');

        add_action('woocommerce_update_options_payment_gateways_' . $this->id, array($this, 'process_admin_options'));
    }

    public function init_form_fields()
    {
        $this->form_fields = array(
            'enabled' => array(
                'title' => __('Enable/Disable', 'paymos-woocommerce'),
                'type' => 'checkbox',
                'label' => __('Enable Paymos payments', 'paymos-woocommerce'),
                'default' => 'no',
            ),
            'title' => array(
                'title' => __('Title', 'paymos-woocommerce'),
                'type' => 'text',
                'default' => __('Pay with stablecoins', 'paymos-woocommerce'),
            ),
            'description' => array(
                'title' => __('Description', 'paymos-woocommerce'),
                'type' => 'textarea',
                'default' => __('Pay with USDT, USDC, DAI and other stablecoins on Tron, Ethereum, BSC, Polygon, Arbitrum, Optimism, Base or TON. No price volatility, no chargebacks, settlement on-chain in minutes.', 'paymos-woocommerce'),
            ),
            'mode' => array(
                'title' => __('Mode', 'paymos-woocommerce'),
                'type' => 'select',
                'default' => 'sandbox',
                'options' => array(
                    'sandbox' => __('Sandbox', 'paymos-woocommerce'),
                    'live' => __('Live', 'paymos-woocommerce'),
                ),
                'description' => esc_html__('The generated Paymos ZIP contains both modes. Switch here when you are ready to process live orders.', 'paymos-woocommerce'),
            ),
            'webhook_url' => array(
                'title' => __('Webhook URL', 'paymos-woocommerce'),
                'type' => 'paymos_webhook_url',
                'description' => esc_html__('Paymos dashboard registers this URL automatically when the plugin ZIP is generated.', 'paymos-woocommerce'),
            ),
            'config_status' => array(
                'title' => __('Generated config', 'paymos-woocommerce'),
                'type' => 'paymos_config_status',
                'description' => esc_html__('API credentials and webhook secrets are generated by Paymos dashboard and are not editable in WordPress.', 'paymos-woocommerce'),
            ),
            'debug_logging' => array(
                'title' => __('Debug logging', 'paymos-woocommerce'),
                'type' => 'checkbox',
                'label' => __('Write Paymos logs to WooCommerce logs', 'paymos-woocommerce'),
                'default' => 'no',
            ),
        );
    }

    public function process_payment($order_id)
    {
        $order = wc_get_order($order_id);
        if (!$order) {
            wc_add_notice(__('Paymos payment error: order not found.', 'paymos-woocommerce'), 'error');
            return array('result' => 'failure');
        }

        try {
            $environment = Config::mode();
            $config = $this->activeEnvironmentConfig($environment);
            $externalOrderId = $this->externalOrderId($order);

            $payload = array(
                'project_id' => (string) $config['project_id'],
                'amount' => OrderAmountGuard::formatAmount($order->get_total()),
                'currency' => $order->get_currency(),
                'external_order_id' => $externalOrderId,
            );

            $clientId = $this->clientId($order);
            if ($clientId !== '') {
                $payload['client_id'] = $clientId;
            }

            $invoice = $this->client($config)->invoices()->create($payload);
        } catch (ApiException $e) {
            Logger::error('Paymos invoice create failed: ' . $e->getMessage(), array('order_id' => $order_id));
            wc_add_notice(__('Paymos payment error: unable to create invoice.', 'paymos-woocommerce'), 'error');
            return array('result' => 'failure');
        } catch (\RuntimeException $e) {
            Logger::error('Paymos invoice create failed: ' . $e->getMessage(), array('order_id' => $order_id));
            wc_add_notice(__('Paymos payment error: configuration is invalid.', 'paymos-woocommerce'), 'error');
            return array('result' => 'failure');
        }

        $invoiceId = isset($invoice['invoice_id']) ? (string) $invoice['invoice_id'] : '';
        $paymentUrl = isset($invoice['payment_url']) ? (string) $invoice['payment_url'] : '';

        if ($invoiceId === '' || $paymentUrl === '') {
            wc_add_notice(__('Paymos payment error: invalid invoice response.', 'paymos-woocommerce'), 'error');
            return array('result' => 'failure');
        }

        $order->update_meta_data('_paymos_invoice_id', $invoiceId);
        $order->update_meta_data('_paymos_external_order_id', $externalOrderId);
        $order->update_meta_data('_paymos_payment_url', $paymentUrl);
        $order->update_meta_data('_paymos_environment', $environment);
        $order->update_meta_data('_paymos_project_id', (string) $config['project_id']);
        OrderAmountGuard::capture($order, $order->get_total(), $order->get_currency());
        $order->update_status('on-hold', __('Awaiting Paymos payment.', 'paymos-woocommerce'));
        $order->save();

        Logger::info('Paymos invoice created.', array(
            'order_id' => (string) $order_id,
            'invoice_id' => $invoiceId,
            'environment' => $environment,
            'project_id' => (string) $config['project_id'],
            'amount' => OrderAmountGuard::formatAmount($order->get_total()),
            'currency' => (string) $order->get_currency(),
        ));

        WC()->cart->empty_cart();

        return array(
            'result' => 'success',
            'redirect' => $paymentUrl,
        );
    }

    /**
     * @param array<string, mixed> $config
     */
    private function client(array $config)
    {
        return new Client(new ClientConfig(
            (string) $config['api_key'],
            (string) $config['api_secret'],
            (string) $config['base_url'],
            30
        ));
    }

    /**
     * @return array<string, mixed>
     */
    private function activeEnvironmentConfig($environment)
    {
        $config = Config::environment_config($environment);
        foreach (array('api_key', 'api_secret', 'project_id', 'base_url') as $required) {
            if (!isset($config[$required]) || !is_scalar($config[$required]) || trim((string) $config[$required]) === '') {
                throw new \RuntimeException('Paymos generated config is missing ' . $required . ' for ' . $environment . '.');
            }
        }

        return $config;
    }

    private function externalOrderId($order)
    {
        $base = 'wc_' . $order->get_id() . '_' . $order->get_order_key();

        if (!method_exists($order, 'get_meta')) {
            return $base;
        }

        $existing = (string) $order->get_meta('_paymos_external_order_id', true);
        if ($existing !== '' && OrderAmountGuard::currentMatchesSnapshot($order)) {
            return $existing;
        }

        if ($existing !== '') {
            return $base . '_' . time();
        }

        return $base;
    }

    private function clientId($order)
    {
        if (!method_exists($order, 'get_customer_id')) {
            return '';
        }

        $customerId = trim((string) $order->get_customer_id());
        return $customerId !== '' && $customerId !== '0' ? $customerId : '';
    }

    public function generate_paymos_webhook_url_html($key, $data)
    {
        $fieldKey = $this->get_field_key($key);
        $url = Config::webhook_url();

        return '<tr valign="top">'
            . '<th scope="row" class="titledesc"><label for="' . esc_attr($fieldKey) . '">' . esc_html($data['title']) . '</label></th>'
            . '<td class="forminp">'
            . '<input class="input-text regular-input" type="text" readonly="readonly" id="' . esc_attr($fieldKey) . '" value="' . esc_attr($url) . '" onclick="this.select();" />'
            . '<p class="description">' . esc_html($data['description']) . '</p>'
            . '</td>'
            . '</tr>';
    }

    public function generate_paymos_config_status_html($key, $data)
    {
        $fieldKey = $this->get_field_key($key);
        $mode = Config::mode();
        $sandbox = Config::has_environment('sandbox') ? __('Configured', 'paymos-woocommerce') : __('Missing', 'paymos-woocommerce');
        $live = Config::has_environment('live') ? __('Configured', 'paymos-woocommerce') : __('Missing', 'paymos-woocommerce');
        $active = Config::environment_config($mode);
        $projectId = isset($active['project_id']) && is_scalar($active['project_id']) ? (string) $active['project_id'] : '';
        $maskedKey = Config::masked_api_key($mode);

        $rows = array(
            __('Active mode', 'paymos-woocommerce') => $mode,
            __('Sandbox', 'paymos-woocommerce') => $sandbox,
            __('Live', 'paymos-woocommerce') => $live,
            __('Active API key', 'paymos-woocommerce') => $maskedKey,
            __('Project ID', 'paymos-woocommerce') => $projectId,
        );

        $html = '<tr valign="top">'
            . '<th scope="row" class="titledesc"><label for="' . esc_attr($fieldKey) . '">' . esc_html($data['title']) . '</label></th>'
            . '<td class="forminp">'
            . '<table class="widefat striped" id="' . esc_attr($fieldKey) . '">';

        foreach ($rows as $label => $value) {
            if ($value === '') {
                $value = __('Missing', 'paymos-woocommerce');
            }

            $html .= '<tr><th style="width: 180px;">' . esc_html($label) . '</th><td><code>' . esc_html($value) . '</code></td></tr>';
        }

        $html .= '</table><p class="description">' . esc_html($data['description']) . '</p></td></tr>';
        return $html;
    }
}
